### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mdolsma** [Novalnet-AG/odoo-payment-integration-novalnet-16#2]
Dear Novalnet,

We are planning to trial the Novalnet payment provider for Odoo 16. After uploading the module to our server, the installation failed. See the full stack trace below.

It seems that the file `wizards/payment_link_wizard_views.xml` mentioned in the manifest file is not present in the repository.

Version = 3.0.0

Could you check this please?

Regards,
Matthijs Dolsma
FindSolutionAI Ltd.

### Stacktrace:
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1864, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 599, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 757, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 209, in file_open
    path = file_path(name, filter_ext=filter_ext, env=env)
  File "/usr/lib/python3/dist-packages/odoo/tools/misc.py", line 188, in file_path
    raise FileNotFoundError("File not found: " + file_path)
FileNotFoundError: File not found: payment_novalnet/wizards/payment_link_wizard_views.xml

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (https://www.erp.findsolutionai.com/web/assets/674-803cd3e/web.assets_backend.min.js:993:163)
    at XMLHttpRequest.<anonymous> (https://www.erp.findsolutionai.com/web/assets/674-803cd3e/web.assets_backend.min.js:1001:13)

**Comment by Novalnet-Technic** [comment]
Dear Matthijs Dolsma,

Upon reviewing your message, we have identified a solution to address the installation issue.

We have updated the **manifest.py** file to ensure proper installation, and we can confirm that the module is now functioning correctly on our end.

To resolve the installation issue on your server, we kindly ask you to update the **manifest.py** file accordingly. This should resolve the issue and allow you to successfully install the Novalnet payment provider module for Odoo 16.

--
Regards,
Novalnet Team
